name = "github-persona"
compatibility_date = "2024-11-24"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

[vars]
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""
REDIRECT_URI = "http://localhost:5173/callback"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "github-persona"
database_id = "00000000-0000-0000-0000-000000000000"

[ai]
binding = "AI"